# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV['DEV_SECRET_KEY_BASE'] %>
  vk_storage_id: <%= ENV['VK_STORAGE_ID'] %>
  fb_user_id: <%= ENV['FB_USER_ID'] %>
  fb_storage_id: <%= ENV['FB_STORAGE_ID'] %>
  fb_access_token: <%= ENV['FB_ACCESS_TOKEN'] %>
  vk_access_token: <%= ENV['VK_ACCESS_TOKEN'] %>

test:
  secret_key_base: <%= ENV['TEST_SECRET_KEY_BASE'] %>
  vk_storage_id: <%= ENV['VK_STORAGE_ID'] %>
  fb_user_id: <%= ENV['FB_USER_ID'] %>
  fb_storage_id: <%= ENV['FB_STORAGE_ID'] %>
  fb_access_token: <%= ENV['FB_ACCESS_TOKEN'] %>
  vk_access_token: <%= ENV['VK_ACCESS_TOKEN'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['PROD_SECRET_KEY_BASE'] %>
  vk_storage_id: <%= ENV['VK_STORAGE_ID'] %>
  fb_user_id: <%= ENV['FB_USER_ID'] %>
  fb_storage_id: <%= ENV['FB_STORAGE_ID'] %>
  fb_access_token: <%= ENV['FB_ACCESS_TOKEN'] %>
  vk_access_token: <%= ENV['VK_ACCESS_TOKEN'] %>
