# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ccd35894436e98912832ce87e7208b5a40c561a6a8d5c450ded4db04e269396dbee3299b791bb3616d2d3bd3c08dc3747bcedbb1e0090f68111070a1c751cd
  vk_storage_id: -75576142
  fb_user_id: 508619002605609
  fb_storage_id: 712139262172677
  fb_access_token: CAAVnU4MCVZCoBANz4C46hDDjZA46ilCheGZBrBkHOroNnmK19exxNZAzodivr7Xhytr3Br67uZA8GNOSjejZCwScmwVHOohjDdevyyV64ZAYyWJqL0rmKuvwzzMKIgKZCBiZATRNjJNoo7y8uJjfPAP3tPhWfDr0QlV7qD1HfT07YGZBo3KFiMcFkLyPrDOMu0fHtb1FZBLZCe8NR3Pstkid0IoYYGvuXNWk5XQZD
  vk_access_token: d9eda0bc61d969da3688bce79ec2357e728fafe5605c4405f52f0ef26bd071134a1d0ebeccb19ef38975d

test:
  secret_key_base: 80aef90283bf19502b866f86a02712015d252c3fd8c81bc9e693e851f4918c78d2ec47e5a9568de1a5fb1f3be2f460e4115f022b1efe219cea3fe19ca3c04ece
  vk_storage_id: -75576142
  fb_user_id: 508619002605609
  fb_storage_id: 712139262172677
  fb_access_token: CAAVnU4MCVZCoBANz4C46hDDjZA46ilCheGZBrBkHOroNnmK19exxNZAzodivr7Xhytr3Br67uZA8GNOSjejZCwScmwVHOohjDdevyyV64ZAYyWJqL0rmKuvwzzMKIgKZCBiZATRNjJNoo7y8uJjfPAP3tPhWfDr0QlV7qD1HfT07YGZBo3KFiMcFkLyPrDOMu0fHtb1FZBLZCe8NR3Pstkid0IoYYGvuXNWk5XQZD
  vk_access_token: d9eda0bc61d969da3688bce79ec2357e728fafe5605c4405f52f0ef26bd071134a1d0ebeccb19ef38975d
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  vk_storage_id: -75576142
  fb_user_id: 508619002605609
  fb_storage_id: 712139262172677
  fb_access_token: CAAVnU4MCVZCoBANz4C46hDDjZA46ilCheGZBrBkHOroNnmK19exxNZAzodivr7Xhytr3Br67uZA8GNOSjejZCwScmwVHOohjDdevyyV64ZAYyWJqL0rmKuvwzzMKIgKZCBiZATRNjJNoo7y8uJjfPAP3tPhWfDr0QlV7qD1HfT07YGZBo3KFiMcFkLyPrDOMu0fHtb1FZBLZCe8NR3Pstkid0IoYYGvuXNWk5XQZD
  vk_access_token: d9eda0bc61d969da3688bce79ec2357e728fafe5605c4405f52f0ef26bd071134a1d0ebeccb19ef38975d
  secret_key_base: 19ccd35894436e98912832ce87e7208b5a40c561a6a8d5c450ded4db04e269396dbee3299b791bb3616d2d3bd3c08dc3747bcedbb1e0090f68111070a1c751cd