# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ccd35894436e98912832ce87e7208b5a40c561a6a8d5c450ded4db04e269396dbee3299b791bb3616d2d3bd3c08dc3747bcedbb1e0090f68111070a1c751cd
  vk_storage_id: -75576142
  fb_storage_id: 712139262172677
  fb_access_token: CAAVnU4MCVZCoBAM6ufT40LnGShhDjqFIUnJLZBBMGzCUK1T6TIDNkBPyEc3HnJiSmU0vKYIHlYJ5MhITMKDvyF1HiF82uabLB9cQNjHxkRVsNhEE7OyNEUXWyo9nppJDjIZAfsfJMWnZCxR0XLvDUGoe7ZCzQ7sLVMBE57cckcxiYwbDbT6DA62VukgxvuiR5Xv5IbNuE3MzMTHZAkzsVZAMwFeMvf2UC0ZD
  vk_access_token: 9ae9b6043c71834abcd43ffffa204d28e372035af01b56ed4e10a29832e2275828fcfda8b057220682f3f

test:
  secret_key_base: 80aef90283bf19502b866f86a02712015d252c3fd8c81bc9e693e851f4918c78d2ec47e5a9568de1a5fb1f3be2f460e4115f022b1efe219cea3fe19ca3c04ece
  vk_storage_id: -75576142
  fb_storage_id: 712139262172677
  fb_access_token: CAAVnU4MCVZCoBAM6ufT40LnGShhDjqFIUnJLZBBMGzCUK1T6TIDNkBPyEc3HnJiSmU0vKYIHlYJ5MhITMKDvyF1HiF82uabLB9cQNjHxkRVsNhEE7OyNEUXWyo9nppJDjIZAfsfJMWnZCxR0XLvDUGoe7ZCzQ7sLVMBE57cckcxiYwbDbT6DA62VukgxvuiR5Xv5IbNuE3MzMTHZAkzsVZAMwFeMvf2UC0ZD
  vk_access_token: 9ae9b6043c71834abcd43ffffa204d28e372035af01b56ed4e10a29832e2275828fcfda8b057220682f3f
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  vk_storage_id: -75576142
  fb_storage_id: 712139262172677
  fb_access_token: CAAVnU4MCVZCoBAM6ufT40LnGShhDjqFIUnJLZBBMGzCUK1T6TIDNkBPyEc3HnJiSmU0vKYIHlYJ5MhITMKDvyF1HiF82uabLB9cQNjHxkRVsNhEE7OyNEUXWyo9nppJDjIZAfsfJMWnZCxR0XLvDUGoe7ZCzQ7sLVMBE57cckcxiYwbDbT6DA62VukgxvuiR5Xv5IbNuE3MzMTHZAkzsVZAMwFeMvf2UC0ZD
  vk_access_token: 9ae9b6043c71834abcd43ffffa204d28e372035af01b56ed4e10a29832e2275828fcfda8b057220682f3f
  secret_key_base: 19ccd35894436e98912832ce87e7208b5a40c561a6a8d5c450ded4db04e269396dbee3299b791bb3616d2d3bd3c08dc3747bcedbb1e0090f68111070a1c751cd